### ISSUE TITLE
Create a code of conduct

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/.github#10]
The contributing guide references to a code of conduct that we don't have yet.

Should we make an organization wide one?

**Comment by laurabrenskelle** [comment]
This seems like a good solution to me. An IOOS code of conduct to apply to all of the IOOS repos.

**Comment by MathewBiddle** [comment]
https://opensource.guide/code-of-conduct/

**Comment by MathewBiddle** [comment]
I like the [Contributor Covenant](https://www.contributor-covenant.org/) in html [here](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).

**Comment by MathewBiddle** [comment]
@ocefpaf @mwengren we should probably iterate on this. Especially the enforcement part of the document. Open to suggestions.
